version: '3.8'

services:
  kali1:
    build:
      context: .
      dockerfile: Dockerfile.sshd
    container_name: kali1
    ports:
      - "2222:22"
    networks:
      - botnet_network

  kali2:
    build:
      context: .
      dockerfile: Dockerfile.sshd
    container_name: kali2
    ports:
      - "2221:22"
    networks:
      - botnet_network

  kali3:
    build:
      context: .
      dockerfile: Dockerfile.sshd
    container_name: kali3
    ports:
      - "2220:22"
    networks:
      - botnet_network

  kali4:
    build:
      context: .
      dockerfile: Dockerfile.sshd
    container_name: kali4
    ports:
      - "2219:22"
    networks:
      - botnet_network

  kali5:
    build:
      context: .
      dockerfile: Dockerfile.sshd
    container_name: kali5
    ports:
      - "2218:22"
    networks:
      - botnet_network

networks:
  botnet_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.139.0/24 