FROM kalilinux/kali-last-release:latest

RUN apt update \
    && apt install -y openssh-server sudo \
    && echo "root:password" | chpasswd \
    && ssh-keygen -A \
    && sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"] 