# Generated by Django 4.2.7 on 2025-06-04 11:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommandHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('container', models.CharField(max_length=100)),
                ('output', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Command Histories',
                'ordering': ['-timestamp'],
            },
        ),
    ]
