# Generated by Django 5.2.2 on 2025-06-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ssh_panel', '0002_delete_commandhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('containers', models.TextField()),
                ('output', models.TextField(blank=True)),
            ],
        ),
    ]
