# Generated by Django 5.2.2 on 2025-06-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssh_panel', '0004_container'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandShortcut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('commands', models.TextField()),
            ],
        ),
    ]
